/* SECURE PORTAL SUBMISSION */
let currentLanguage='ar';
let currentStep=1;
const formData={personalInfo:{},contactCareer:{},grantDetails:{},bankingInfo:{},attachments:{}};

document.addEventListener('DOMContentLoaded',()=>{
  setupLanguageSwitchers(); setupFormListeners(); setupFileUpload(); setupIBANFormatting(); setupOtherFields();
});
function setupLanguageSwitchers(){document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>switchLanguage(b.dataset.lang)));}
function switchLanguage(lang){currentLanguage=lang;document.querySelectorAll('[data-en][data-ar]').forEach(el=>{const t=lang==='en'?el.dataset.en:el.dataset.ar;if(el.tagName==='INPUT'||el.tagName==='TEXTAREA')el.placeholder=t;else el.textContent=t;});document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';}
function nextStep(){if(validateStep(currentStep)){saveStepData(currentStep);currentStep=Math.min(currentStep+1,5);updateProgressBar();showStep(currentStep);}}
function prevStep(){saveStepData(currentStep);currentStep=Math.max(currentStep-1,1);updateProgressBar();showStep(currentStep);}
function showStep(n){document.querySelectorAll('.form-step').forEach(s=>s.classList.remove('active'));document.getElementById('formStep'+n)?.classList.add('active');}
function updateProgressBar(){const p=document.getElementById('progressFill');if(p)p.style.width=(currentStep/5*100)+'%';}
function validateField(f){const v=f.value.trim();let ok=!!v,msg='';if(ok&&f.type==='email')ok=/^([^\s@]+)@([^\s@]+)\.([^\s@]+)$/.test(v);if(ok&&f.name==='phone')ok=/^\+?[0-9\s\-()]{10,20}$/.test(v);if(ok&&f.name==='iban')ok=/^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$/.test(v.replace(/\s/g,''));if(ok&&(f.name==='grantAmount'||f.name==='income'))ok=Number(v)>0;if(!ok)msg=currentLanguage==='ar'?'يرجى تصحيح الحقل':'Please correct this field';const e=f.closest('.form-group')?.querySelector('.error-message');if(e)e.textContent=ok?'':msg;f.classList.toggle('error',!ok);return ok;}
function validateStep(n){const step=document.getElementById('formStep'+n);if(!step)return false;let ok=true;step.querySelectorAll('[required]').forEach(f=>{if(f.type==='file'||f.type==='checkbox')return;if(!validateField(f))ok=false;});if(n===5){for(const id of ['idCardFront','idCardBack']){const e=document.getElementById(id+'Error');if(!formData.attachments[id]){if(e)e.textContent=currentLanguage==='ar'?'يرجى رفع هذه الصورة':'Please upload this photo';ok=false;}else if(e)e.textContent='';}const terms=document.getElementById('terms');if(terms&&!terms.checked)ok=false;}return ok;}
function saveStepData(n){const step=document.getElementById('formStep'+n);const groups=[null,formData.personalInfo,formData.contactCareer,formData.grantDetails,formData.bankingInfo];const g=groups[n];if(!step||!g)return;step.querySelectorAll('input,select,textarea').forEach(i=>{if(i.type==='file'||i.type==='checkbox')return;if(i.name)g[i.name]=i.value;});}
function setupFileUpload(){for(const id of ['idCardFront','idCardBack']){const i=document.getElementById(id);if(i)i.addEventListener('change',()=>{const f=i.files?.[0];if(f)processFile(f,id,i);});}}
function processFile(f,id,i){const e=document.getElementById(id+'Error');if(f.size>5*1024*1024){if(e)e.textContent='حجم الملف أكبر من 5 ميجابايت';i.value='';delete formData.attachments[id];return;}if(!['image/jpeg','image/png','image/webp'].includes(f.type)){if(e)e.textContent='يُسمح فقط بصور JPG أو PNG أو WebP';i.value='';delete formData.attachments[id];return;}if(e)e.textContent='';formData.attachments[id]=f;const p=document.getElementById(id+'Preview');if(p){p.textContent='✓ '+f.name;p.style.display='block';}}
function setupIBANFormatting(){const i=document.getElementById('iban');if(!i)return;i.addEventListener('input',()=>{let v=i.value.toUpperCase().replace(/\s/g,'').replace(/[^A-Z0-9]/g,'').slice(0,34);i.value=(v.match(/.{1,4}/g)||[]).join(' ');});}
function setupOtherFields(){const c=document.getElementById('country'),oc=document.getElementById('otherCountryGroup'),oi=document.getElementById('otherCountry');if(c&&oc&&oi)c.addEventListener('change',()=>{const o=c.value==='OTHER';oc.style.display=o?'block':'none';oi.required=o;if(!o)oi.value='';});const b=document.getElementById('bankName'),ob=document.getElementById('otherBankGroup'),oi2=document.getElementById('otherBank');if(b&&ob&&oi2)b.addEventListener('change',()=>{const o=b.value==='OTHER';ob.style.display=o?'block':'none';oi2.required=o;if(!o)oi2.value='';});}
function getBlobExtension(file){return {'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type]||'bin';}
async function uploadPrivateIdentityImage(applicationId,fieldName,file){const mod=window.__vercelBlobModule||(window.__vercelBlobModule=await import('https://esm.sh/@vercel/blob@2.3.0/client'));const result=await mod.upload(`applications/${applicationId}/${fieldName}.${getBlobExtension(file)}`,file,{access:'private',handleUploadUrl:'/api/blob-upload',contentType:file.type,clientPayload:JSON.stringify({applicationId,fieldName,contentType:file.type,size:file.size})});return{pathname:result.pathname,contentType:result.contentType||file.type,size:file.size};}
function collectApplicationPayload(){for(const n of [1,2,3,4])saveStepData(n);return{personalInfo:formData.personalInfo,contactCareer:formData.contactCareer,grantDetails:formData.grantDetails,bankingInfo:formData.bankingInfo};}
async function submitApplicationSecurely(txNumber){const applicationId=crypto.randomUUID();const images={};for(const fieldName of ['idCardFront','idCardBack']){const f=formData.attachments[fieldName];if(!f)throw new Error('Missing '+fieldName);images[fieldName]=await uploadPrivateIdentityImage(applicationId,fieldName,f);}const r=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId,transactionNumber:txNumber,payload:collectApplicationPayload(),images})});const result=await r.json().catch(()=>({}));if(!r.ok||!result.ok){const e=new Error(result.error||'Application save failed');e.stage=result.stage;throw e;}return result;}
function setupFormListeners(){const b=document.getElementById('submitBtn');if(!b)return;b.addEventListener('click',async()=>{if(!validateStep(5))return;saveStepData(5);b.disabled=true;b.textContent='جاري الحفظ...';const tx='WA-'+new Date().getFullYear()+'-'+String(Math.floor(Math.random()*90000)+10000);try{await submitApplicationSecurely(tx);}catch(e){console.error(e);alert((e.message||'تعذر حفظ الطلب')+(e.stage?' ['+e.stage+']':''));b.disabled=false;b.textContent='تقديم الطلب';return;}b.disabled=false;b.textContent='تقديم الطلب';document.getElementById('transactionNumber')?.replaceChildren(document.createTextNode(tx));document.getElementById('successModal')?.classList.add('active');});}
document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('input:not([type=file]),select,textarea').forEach(f=>f.addEventListener('blur',()=>{if(f.required)validateField(f);})));