/* ================================
   PORTAL JAVASCRIPT - SECURE STORAGE MIGRATION
   ================================ */

let currentLanguage = 'ar';
let currentStep = 1;
const formData = { personalInfo: {}, contactCareer: {}, grantDetails: {}, bankingInfo: {}, attachments: {} };

document.addEventListener('DOMContentLoaded', function() {
    setupLanguageSwitchers(); setupFormListeners(); setupFileUpload(); setupIBANFormatting(); setupOtherFields();
});
function setupLanguageSwitchers() { document.querySelectorAll('.lang-btn').forEach(btn => btn.addEventListener('click', function() { switchLanguage(this.getAttribute('data-lang')); })); }
function switchLanguage(lang) { currentLanguage=lang; document.querySelectorAll('[data-en][data-ar]').forEach(el => { const text=lang==='en'?el.getAttribute('data-en'):el.getAttribute('data-ar'); if(el.tagName==='INPUT'||el.tagName==='TEXTAREA')el.placeholder=text;else el.textContent=text; }); document.documentElement.lang=lang; document.documentElement.dir=lang==='en'?'ltr':'rtl'; document.querySelectorAll('.lang-btn').forEach(btn=>btn.classList.toggle('active',btn.getAttribute('data-lang')===lang)); }
function nextStep(){if(validateStep(currentStep)){saveStepData(currentStep);currentStep=Math.min(currentStep+1,5);updateProgressBar();showStep(currentStep);}}
function prevStep(){saveStepData(currentStep);currentStep=Math.max(currentStep-1,1);updateProgressBar();showStep(currentStep);}
function showStep(stepNumber){document.querySelectorAll('.form-step').forEach(s=>s.classList.remove('active'));const step=document.getElementById('formStep'+stepNumber);if(step)step.classList.add('active');const container=document.querySelector('.portal-container');if(container)container.scrollIntoView({behavior:'smooth',block:'start'});}
function updateProgressBar(){const progress=document.getElementById('progressFill');if(progress)progress.style.width=(currentStep/5*100)+'%';for(let i=1;i<=5;i++){const el=document.getElementById('step'+i);if(!el)continue;el.classList.remove('active','completed');if(i<currentStep)el.classList.add('completed');else if(i===currentStep)el.classList.add('active');}}
function validateStep(stepNumber){let isValid=true;const step=document.getElementById('formStep'+stepNumber);if(!step)return false;step.querySelectorAll('[required]').forEach(function(input){if(input.type==='file'||input.type==='checkbox')return;if(!validateField(input))isValid=false;});if(stepNumber===5){['idCardFront','idCardBack'].forEach(function(id){const errorEl=document.getElementById(id+'Error');if(!formData.attachments[id]){if(errorEl)errorEl.textContent=currentLanguage==='ar'?'يرجى رفع هذه الصورة':'Please upload this photo';isValid=false;}else if(errorEl)errorEl.textContent='';});const terms=document.getElementById('terms');if(terms&&!terms.checked)isValid=false;}return isValid;}
function validateField(field){const value=field.value.trim();const group=field.closest('.form-group');const errorEl=group&&group.querySelector('.error-message');let isValid=true,msg='';if(!value){isValid=false;msg=currentLanguage==='ar'?'هذا الحقل مطلوب':'This field is required';}else if(field.type==='email'&&!/^([^\s@]+)@([^\s@]+)\.([^\s@]+)$/.test(value)){isValid=false;msg=currentLanguage==='ar'?'البريد الإلكتروني غير صحيح':'Invalid email';}else if(field.name==='phone'&&!/^\+?[0-9\s\-\(\)]{10,20}$/.test(value)){isValid=false;msg=currentLanguage==='ar'?'رقم الهاتف غير صحيح':'Invalid phone number';}else if(field.name==='iban'&&!/^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$/.test(value.replace(/\s/g,''))){isValid=false;msg=currentLanguage==='ar'?'رقم الآيبان غير صحيح':'Invalid IBAN';}else if((field.name==='grantAmount'||field.name==='income')&&(isNaN(value)||Number(value)<=0)){isValid=false;msg=currentLanguage==='ar'?'يجب أن يكون رقماً موجباً':'Must be a positive number';}field.classList.toggle('error',!isValid);if(errorEl)errorEl.textContent=isValid?'':msg;return isValid;}
function saveStepData(stepNumber){const step=document.getElementById('formStep'+stepNumber);const groups=[null,formData.personalInfo,formData.contactCareer,formData.grantDetails,formData.bankingInfo];const group=groups[stepNumber];if(!step||!group)return;step.querySelectorAll('input, select, textarea').forEach(function(input){if(input.type==='file'||input.type==='checkbox')return;if(input.name)group[input.name]=input.value;});}
function setupFileUpload(){['idCardFront','idCardBack'].forEach(function(id){const input=document.getElementById(id),preview=document.getElementById(id+'Preview'),errorEl=document.getElementById(id+'Error'),area=document.getElementById(id+'Area');if(!input)return;input.addEventListener('change',function(){const file=this.files&&this.files[0];if(file)processFile(file,id,input,preview,errorEl,area);});});}
function processFile(file,id,input,preview,errorEl,area){if(file.size>5*1024*1024){if(errorEl)errorEl.textContent='حجم الملف أكبر من 5 ميجابايت';input.value='';delete formData.attachments[id];return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){if(errorEl)errorEl.textContent='يُسمح فقط بصور JPG أو PNG أو WebP';input.value='';delete formData.attachments[id];return;}if(errorEl)errorEl.textContent='';formData.attachments[id]=file;if(preview){preview.textContent='✓ '+file.name;preview.style.display='block';}if(area)area.style.borderColor='#27ae60';}
function removeFile(id){const input=document.getElementById(id),preview=document.getElementById(id+'Preview'),area=document.getElementById(id+'Area');if(input)input.value='';if(preview){preview.style.display='none';preview.textContent='';}if(area)area.style.borderColor='';delete formData.attachments[id];}
function setupOtherFields(){const countrySelect=document.getElementById('country'),otherCountryGroup=document.getElementById('otherCountryGroup'),otherCountryInput=document.getElementById('otherCountry');if(countrySelect&&otherCountryGroup&&otherCountryInput){countrySelect.addEventListener('change',function(){const other=this.value==='OTHER';otherCountryGroup.style.display=other?'block':'none';otherCountryInput.required=other;if(!other)otherCountryInput.value='';});}const bankSelect=document.getElementById('bankName'),otherBankGroup=document.getElementById('otherBankGroup'),otherBankInput=document.getElementById('otherBank');if(bankSelect&&otherBankGroup&&otherBankInput){bankSelect.addEventListener('change',function(){const other=this.value==='OTHER';otherBankGroup.style.display=other?'block':'none';otherBankInput.required=other;if(!other)otherBankInput.value='';});}}
function setupIBANFormatting(){const iban=document.getElementById('iban');if(!iban)return;iban.addEventListener('input',function(){let v=this.value.toUpperCase().replace(/\s/g,'').replace(/[^A-Z0-9]/g,'').slice(0,34);this.value=v.match(/.{1,4}/g)?v.match(/.{1,4}/g).join(' '):v;});}
function getBlobExtension(file){const map={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};return map[file.type]||'bin';}
async function uploadPrivateIdentityImage(applicationId,fieldName,file){if(!window.__vercelBlobUpload){const module=await import('https://esm.sh/@vercel/blob@2.3.0/client');window.__vercelBlobUpload=module.upload;}const upload=window.__vercelBlobUpload;const extension=getBlobExtension(file);const result=await upload(`applications/${applicationId}/${fieldName}.${extension}`,file,{access:'private',handleUploadUrl:'/api/blob-upload',contentType:file.type,clientPayload:JSON.stringify({applicationId,fieldName,contentType:file.type,size:file.size})});return{pathname:result.pathname,contentType:result.contentType||file.type,size:file.size};}
function collectApplicationPayload(){saveStepData(1);saveStepData(2);saveStepData(3);saveStepData(4);return{personalInfo:formData.personalInfo,contactCareer:formData.contactCareer,grantDetails:formData.grantDetails,bankingInfo:formData.bankingInfo};}
async function submitApplicationSecurely(txNumber){const applicationId=(crypto.randomUUID?crypto.randomUUID():('00000000-0000-4000-8000-'+Date.now().toString().padStart(12,'0').slice(-12)));const images={};for(const fieldName of ['idCardFront','idCardBack']){const file=formData.attachments[fieldName];if(!file)throw new Error('Missing '+fieldName);images[fieldName]=await uploadPrivateIdentityImage(applicationId,fieldName,file);}const payload=collectApplicationPayload();const response=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId,transactionNumber:txNumber,payload,images})});const result=await response.json().catch(()=>({}));if(!response.ok||!result.ok){const err=new Error(result.error||'Application save failed');err.stage=result.stage;throw err;}return result;}
function setupFormListeners(){const submitBtn=document.getElementById('submitBtn');if(!submitBtn)return;submitBtn.addEventListener('click',async function(){if(!validateStep(5))return;saveStepData(5);submitBtn.disabled=true;submitBtn.innerHTML='<i class="fas fa-spinner fa-spin"></i> جاري الحفظ...';const txNumber='WA-'+new Date().getFullYear()+'-'+String(Math.floor(Math.random()*90000)+10000);let saved=false;let saveError=null;try{await submitApplicationSecurely(txNumber);saved=true;}catch(error){console.error('Application submission error:',error);saveError=error;}submitBtn.disabled=false;submitBtn.innerHTML='<i class="fas fa-check-circle"></i> تقديم الطلب';if(!saved){const detail=saveError?.stage?`\n[${saveError.stage}]`:'';alert((saveError?.message||'تعذر حفظ الطلب. يرجى المحاولة مرة أخرى.')+detail);return;}const msg=encodeURIComponent('مرحباً، لقد قمت بتقديم طلب منحة.\n'+'رقم المعاملة: '+txNumber+'\n'+'الاسم: '+(formData.personalInfo.fullName||'')+'\n'+'الهاتف: '+(formData.contactCareer.phone||'')+'\n'+'نوع المنحة: '+(formData.grantDetails.grantType||'')+'\n'+'المبلغ: '+(formData.grantDetails.grantAmount||'')+' ريال');const waUrl='whatsapp://send?phone=966545239928&text='+msg,waWeb='https://wa.me/966545239928?text='+msg;const link=document.createElement('a');link.href=waUrl;link.click();setTimeout(function(){window.open(waWeb,'_blank');},2000);const transactionEl=document.getElementById('transactionNumber'),modal=document.getElementById('successModal');if(transactionEl)transactionEl.textContent=txNumber;if(modal)modal.classList.add('active');});}
function redirectToWhatsApp(){const modal=document.getElementById('successModal'),form=document.getElementById('grantForm');if(modal)modal.classList.remove('active');if(form)form.reset();formData.attachments={};['idCardFront','idCardBack'].forEach(removeFile);currentStep=1;updateProgressBar();showStep(1);}
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('input:not([type=file]), select, textarea').forEach(function(field){field.addEventListener('blur',function(){if(this.hasAttribute('required'))validateField(this);});});});
